import Head from 'next/head'
let JSZip = require('jszip');
import styles from '../styles/Home.module.css'
import { Form, Button, Row, Col } from 'react-bootstrap'
import imageCompression from 'browser-image-compression';
import { useState } from 'react';
import ClipLoader from "react-spinners/ClipLoader";


export default function Home() {
  const [images, setImage] = useState(null)
  const [visibility, setVisibility] = useState("none")
  const [loading, setLoading] = useState(false)
  const [files, setFiles] = useState(null)

  const loadingHandler = (l) => {
    if (l) {
      setLoading(false)
      setVisibility("block")
    }
    else {
      setLoading(true)
      setVisibility("none")
    }
  }

  async function upFoto(event) {
    loadingHandler(false)
    var files = []
    var imagesb64 = []
    for (var image of event.target.files) {
      const imageFile = image;
      const options = {
        useWebWorker: true
      }
      try {
        const compressedFile = await imageCompression(imageFile, options);
        files.push({ image: compressedFile, name: imageFile.name })
        var image = await imageCompression.getDataUrlFromFile(compressedFile);
        imagesb64.push({ image: image, name: imageFile.name })
      } catch (error) {
        console.log(error);
      }
    }
    setImage(imagesb64);
    setFiles(files);
    loadingHandler(true)
  }

  function downloadAll() {
    var link = document.createElement('a');
    link.style.display = 'none';
    document.body.appendChild(link);
    for (var n of images) {
      link.setAttribute('download', n.name);
      link.setAttribute('href', n.image);
      link.click();
    }
    document.body.removeChild(link);
  }

  function downloadZip() {
    let zip = new JSZip()
    for (var i of files) {
      zip.file(i.name, i.image);
    }
    zip.generateAsync({ type: 'blob' }).then((blobdata) => {
      let zipblob = new Blob([blobdata])
      var elem = window.document.createElement("a")
      elem.href = window.URL.createObjectURL(zipblob)
      elem.download = 'compressed.zip'
      elem.click()
    })
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>RadarFit Compressor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        />
      </Head>

      <Form >
        <Form.File onChange={upFoto} style={{ width: "100%", margin: 20 }} id="file" name="file" multiple />
      </Form>
      <ClipLoader loading={loading} size={15} ></ClipLoader>
      <Row>
        <Col><Button style={{ display: visibility }} variant="outline-dark" onClick={downloadAll}>  Download</Button></Col>
        <Col><Button style={{ display: visibility }} variant="outline-dark" onClick={downloadZip}>  Zip</Button></Col>
      </Row>
    </div>
  )
}
